### ISSUE TITLE
The QR code isn't valid

### ISSUE THREAD

**Issue by 7heo** [almindor/harbour-jTox#17]
The application displays for my key a QR code that mostly looks like a chess board. It's also not working with the QR code readers on android.

**Comment by almindor** [comment]
Checkerboard means "empty". I noticed this happened sometimes, not sure what was the cause tho. Try going in accounts again or restarting jTox and waiting a bit before going in to show the QR code.

I don't know what's the cause yet as the toxid is def. present when it happens. It's probably a QML/databinding issue. Basically an empty toxID is loaded in before the actual toxID becomes available. But it's hard to reproduce.

**Comment by 7heo** [comment]
As of now (my Jolla is currently out of battery) it happened constantly and consistently.  And it happened on two accounts (I trashed my first account (`find -name '*jTox' -exec rm -rf {} \;` in my home) because I forgot the password - I didn't bother to actually use something I'd remember...)

**Comment by almindor** [comment]
Interesting, would it bepossible for you to run the SailfishOS SDK? We could debug on your phone this way..

**Comment by 7heo** [comment]
I could try to do that, but not immediately. For personal reasons this won't be realistic before approximately one month.

**Comment by almindor** [comment]
NOTE: I couldn't consistently reproduce but this should hopefully fix the issue, if you still get it after 1.1.0 release please reopen

**Comment by 7heo** [comment]
I'll test that once I get 1.1.0 from the store.
