### ISSUE TITLE
UI problem - Adding contact

### ISSUE THREAD

**Issue by 7heo** [almindor/harbour-jTox#2]
When adding a contact, it is important that the user doesn't have to press "Enter" (or "Return") after pasting the fingerprint of that contact in order for the key to be validated. It is very impractical and goes against all widely used UX principles.

**Comment by almindor** [comment]
Good point, I'll change it to use onTextChange

**Comment by almindor** [comment]
NOTE: I only did inline validation on full addresses, NOT toxme handles as that would hammer the server too much. User still has to "submit" enter key on toxme.io handle adds

**Comment by 7heo** [comment]
Maybe it would help to wait 3 seconds after the last activity if the input ends with `@toxme.io` (ideally with a graphical progress bar filling during those X seconds so the user gets that something is happening; and even better if the same progress bar starts "cycling" (to show activity but not progress) when the actual submission happens)

**Comment by almindor** [comment]
I might add that. Last remaining thing right now is #12 and I can release 1.0.1

I'm done for today but should be able to close #12 and possibly add a timeout timer for this tomorrow.

**Comment by 7heo** [comment]
Great work! Thanks again.
