### ISSUE TITLE
-Feature---Request+

### ISSUE THREAD

**Issue by ghost** [almindor/harbour-jTox#26]
HI almindor
- I want to make a donation for this app, but I have a lot of difficulty setting up flatt, please provide via paypal on openrepos = )

- can you add  a DAEMON MODE to run in background! > This to get the message in real time, even though the app will close

- can you add the new word in my harbour-jtox-es.ts  to translate ? i am new in github i dont know how do it.

  ONCE AGAIN THANKS FOR UR GREAT WORK!!!

**Comment by almindor** [comment]
Hey, I don't do paypal anymore, had issues with them in the past. I can provide a bitcoin address if that's doable :)

The daemon mode is a TODO item for version 2.0.0 (see milestones).

Not sure what you mean by adding new word?

**Comment by ghost** [comment]
Not sure what you mean by adding new word?   RE:  i  fixed
- I will continue trying to solve the problem with flatt until I get the donation to your app ; )
