### ISSUE TITLE
Does not retain contacts

### ISSUE THREAD

**Issue by 7heo** [almindor/harbour-jTox#3]
If you add a contact to jTox, and then the application gets killed by SailFish for whatever reason, the contact won't be there when you open jTox again. This is a critical issue.

**Comment by 7heo** [comment]
The same way the contacts are missing, other settings (like the display name) are missing too if the application is preemptively terminated.

**Comment by almindor** [comment]
This is a bug. I should call tox_save after any change, right now it's called as part of the ToxCore object destructor so it won't get called if the app is terminated in a bad way.
