### ISSUE TITLE
update translation string

### ISSUE THREAD

**Issue by ghost** [almindor/harbour-jTox#30]
hello almindor
can you update translation.es files! thanks

**Comment by almindor** [comment]
Not sure what you mean? Is something missing in master?

**Comment by ghost** [comment]
add new string to harbour-jtox-es.ts . one month ago last update. if you update it is easy to me to translate the new string. i know eson already did. but I do not know how he did it.

**Comment by ghost** [comment]
almindor still not understand? > example: unplayer/equeim like this:https://github.com/equeim/unplayer/tree/master/translations

**Comment by almindor** [comment]
Hmm the source strings should update automatically when I build. I think there might be an utility to run to force it I'll look
