### ISSUE TITLE
Spanish translation still not shipped jTox v.1.1.1

### ISSUE THREAD

**Issue by ghost** [almindor/harbour-jTox#37]
- After install  jTox v1.1.1 i  noted spanish not shipped

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
Hello: Almindor 
Any news about jTox? I am still waiting my-es.ts translate :  )

Thanks ...

**Comment by almindor** [comment]
Hey, sorry about the delay, was busy on another project. I'll try to do a release this week.
