### ISSUE TITLE
Importing account without an account?

### ISSUE THREAD

**Issue by dirteat** [almindor/harbour-jTox#44]
Just to say that it is a little confusing to have only the line "enter password" the first ever time you start jTox.

I was looking for a menu to import an account, but it appears only once another account has been created. Would be nice to be able to import an account at the first run!

Thanks.
Cheers.

**Comment by almindor** [comment]
Good point, it's a bit of a "fossil" due to how initialization is being done.

I suppose I could add a button/pulldown menu that will "shortcut" you into the import section.

**Comment by almindor** [comment]
fixed in latest
