### ISSUE TITLE
Double tapping enter crashes jTox.

### ISSUE THREAD

**Issue by patrickrifici** [almindor/harbour-jTox#51]
In the current release of jTox (v1.3.0) with toxcore v0.2.2, double tapping the enter key while in a chat window will cause jTox to crash. Attempting to open jTox afterwards will result in normal function until the contact which was open during the crash comes online, at which point jTox will crash again. The only way to rectify the issue is to delete any jTox data found in .config and .local and then either create a new Tox ID or import a backup.

**Comment by almindor** [comment]
Thanks this was a big oversight on my end.

Toxcore does not allow empty message sends. QML keyboard sends me a message with just `\n` which I trim away and it causes empty message to be forwarded. Same for pending.

I'm about to release 1.3.1 with a fix for this as well as any remaining invalid pending messages. You can also currently work-around the always-crash on pending send by long-pressing the pending message and deleting it. But you need to do this before your friend is registered as being online.

**Comment by almindor** [comment]
Fixed in latest master, will release 1.3.1 shortly

**Comment by ghost** [comment]
Still crashing on accepting transfer in -v 1.3.1 :  (

**Comment by almindor** [comment]
@Caballlero accepting transfer? I think that's a separate issue, this was about sending messages by pressing enter twice. Can you open an issue with details about your crash please?

**Comment by ghost** [comment]
ok
