### ISSUE TITLE
 Crash on accepting transfer in -v 1.3.1

### ISSUE THREAD

**Issue by ghost** [almindor/harbour-jTox#54]

**Comment by almindor** [comment]
Is there any backtrace? Which client did you use to send the file? If not super-private what was the filename/type of the file? Did it crash right when you choose the accept option?

**Comment by ghost** [comment]
I using jTox to jTox, yes is crashing instantly when I accept the tranfer.

**Comment by almindor** [comment]
Hmm interesting, can you add me via toxme.io ? (almindor)

Does the sending side then just keep the transfer in limbo?

**Comment by almindor** [comment]
Just tried with the emulator on one end and my Sony X on the other. Both sides worked ok for me so you're going to have to help me reproduce this.

**Comment by ghost** [comment]
I already send to you the request

**Comment by ghost** [comment]
do you get it my friend request_?

**Comment by ghost** [comment]
will close this issue temporarily...
