### ISSUE TITLE
Chat improvements

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [almindor/harbour-jTox#71]
When friend is offline there is no items in pullup menu but it's still visible and it confuses people.
Second thing is the time. You just pasted timestamp text. We need to split that into time and date to make it more readable (probably let's not add date if it's current day).

PS: I think i will do it :P

**Comment by almindor** [comment]
Good suggestions, I'll try to work on these once I'm done with the audio calls.

**Comment by almindor** [comment]
If you do want to take a stab at this please make a fork of the master branch and go from there.

**Comment by Michal-Szczepaniak** [comment]
That's what i just did :D I'm getting kinda back to Tox probably so i'm gonna give you some love

**Comment by Michal-Szczepaniak** [comment]
@almindor WAIT WHAT?! Audio calls? Are you serious? First sfos app with audio calls?

**Comment by almindor** [comment]
Yes :) I'm fairly close but there's at least a week of work left.

I'm mostly working on UI and state machine handling now (calls, in call , ringing etc.). Didn't try actually reconstruct the audio data yet but I did get in call from both sides now. Also didn't try making the mic work yet.

I've also stumbled upon an MCE proximity sensor and audio sink issue. The guys at #sailfishos on freenode are trying to help there. 

You can check the `av` branch if you want to see a WIP but it's fairly borked atm. Just try on the emulator with qTox if you really want to.

**Comment by Michal-Szczepaniak** [comment]
Well i guess i will leave that to you ;) For development i'm using only devices. I need to dig deeper into your jtox code and try to understand it. 

building everything as we are speaking ;)

**Comment by almindor** [comment]
Sure, I use jolla 1 as dev device and I got a sony xperia x as main. But the emulator is a bit faster I just keep it always on top of the dev window and keep redeploying.

If you do want to help with something feel free to ask, but I'd suggest maybe trying to fix the small issues you reported off the master branch first :)

**Comment by almindor** [comment]
Oh as a side note, the configuration in the .pro file (due to the .a files I link in) is such that `debug` config will always aim for i486 and `release` will go for `armv7hl`.

So if you want a debug build for a device you need to uncomment the other line on the top of the .pro file and comment the one in use right now. As they are set up right now it's:

```
CONFIG(debug,debug|release){ TOX_PATH = extra/i486 }
# CONFIG(debug,debug|release){ TOX_PATH = extra/armv7hl }
CONFIG(release,debug|release){ TOX_PATH = extra/armv7hl }
```

**Comment by Michal-Szczepaniak** [comment]
Yeah i already did that myself year ago ;P

Sure then i'm gonna look into the one year old issue that i created, said i will do it and completely forgot about untill today xd

**Comment by Michal-Szczepaniak** [comment]
@almindor btw is there better way to contact you than github issue?

**Comment by almindor** [comment]
You can also use gitter https://gitter.im/almindor/jtox and I do tend to be on freenode/irc around #sailfishos and others
