### ISSUE TITLE
Avatars are not distinguished from regular file transfers

### ISSUE THREAD

**Issue by moorchegue** [almindor/harbour-jTox#74]
There's an issue that occurs between Toxic and jTox I described here: 

https://github.com/JFreegman/toxic/issues/529

Is it really a jTox / qTox issue or is it possible that something's going on on the Toxic side?

**Comment by almindor** [comment]
Would it be possible for you to debug this issue? I'm currently very short on time, but what we're looking for is info on the received data from toxic when this happens. I never saw this happen with other clients but admittedly I mostly tested against qTox. I know for a fact that when qTox sends avatar updates it works fine with jTox as the receiver so this is a bit confusing.

The logic described by @JFreegman wrt. hashing is also implemented (not copied from QTox as he alleges) and fully understood, although I'm not claiming there can't be a bug.

**Comment by JFreegman** [comment]
This was a toxic bug https://github.com/TokTok/toxic/pull/126

**Comment by almindor** [comment]
> This was a toxic bug [TokTok/toxic#126](https://github.com/TokTok/toxic/pull/126)

Thanks. Closing issue here.
